lib/postgresql.js, test/postgresql.test.js
=> Escape number literals to avoid SQL injection

lib/postgresql.js
=> Use connection pooling from the driver

test/postgresql.filterUndefined.test.js
@raymondfeng, please find extra tests that cover the changes from #54 in a7cd59a as @aars had some concerns about that approach here aol-nnov/loopback-connector-postgresql@bfb3f00.
All test passed.
=> more tests to cover "filter undefined fields" changeset

lib/postgresql.js
See https://groups.google.com/forum/#!topic/loopbackjs/fH0atfJWku4
=> Fix the conversion of point types due to driver changes

README.md
@bajtos @raymondfeng @ritch Can you let me know the details in addition to the ones I've listed to run tests?
Connected to strongloop/loopback#1167
=> Add instructions to running tests section

lib/postgresql.js
- `update/updateAll` returns item count
- `destroyAll` return item count
Connect to strongloop/loopback#1167
=> Return count when updating or deleting

lib/postgresql.js, lib/transaction.js, package.json, test/postgresql.transaction.test.js
/to @ritch @bajtos
This PR adds local transaction apis for relational DBs.
Connect to strongloop/loopback#109
=> Add transaction support

lib/postgresql.js, package.json, test/init.js, test/postgresql.test.js
Connect to strongloop/loopback-datasource-juggler#552
=> Add support for RegExp operator

test/postgresql.test.js
Add tests to ensure regexp operator works properly when flags are provided.
=> Add regexp operator tests

test/postgresql.test.js
Wrap long lines in regexp operator tests.
=> Clean up regexp operator tests

lib/discovery.js, lib/migration.js, test/postgresql.autoupdate.test.js, test/postgresql.migration.test.js
I'm fairly certain this is a mostly functional solution to strongloop#47
=> Index implementation

package.json
Depends on https://github.com/strongloop/loopback-datasource-juggler/pull/804
=> Upgrade should to 8.0.2

lib/migration.js, test/postgresql.autoupdate.test.js
=> Fix typo in SET NOT NULL migration.

lib/migration.js, lib/postgresql.js, test/postgresql.migration.test.js
This is a mergeable update to #153 that also respects dbDefault.
Unfortunately it is not clear how to run tests on this repository.
=> Fix #123: Set default value during autoupdate.

lib/migration.js, lib/postgresql.js, test/postgresql.migration.test.js
This is a mergeable update to #153 that also respects dbDefault.
Backport of #167 
cc @0candy
=> Backport: Set default value during autoupdate.

test/init.js
Backport of #179
cc @strongloop/fa-db-connectors
=> Add connectorCapabilities global object (#179)

README.md
=> update README for local postgres setup

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, README.md, lib/postgresql.js, lib/transaction.js, test/postgresql.test.js, test/postgresql.transaction.test.js
Backport commits after https://github.com/strongloop/loopback-connector-postgresql/commit/613b6ed41ac9ec61d5d7744d538dde013c3fb8f6 from master to 2.x
=> Backport commits to 2.x

lib/migration.js
=> Extract propertyHasNotBeenDeleted to base

lib/discovery.js, test/postgresql.discover.test.js
Refactor discovery test cases
connect to https://github.com/strongloop/loopback-connector/issues/15
=> Refactor discovery models

test/init.js, test/postgresql.dbdefaults.test.js
Fix CI for 2.x, in order to get juggler 2.x CI to pass
- porting changes from master to fix the `too many client` issue
connect to: https://github.com/strongloop/loopback-datasource-juggler/pull/1342
=> [2.x] Fix CI

README.md, setup.sh
=> Fix docker setup

README.md
=> Correct a <td> to </td> closing tag

package.json
Closes https://github.com/strongloop/loopback-connector-postgresql/issues/258
=> Use loopback-connector@^4.2.2

package.json
Drop Node 0.10 and 0.12 in package.json
=> [SEMVER-MAJOR] Drop Node 0.10 and 0.12 in package.json

package.json
- Drop Node 4 in CI
- update dependencies
=> chore: Drop Node 4 in CI

CODEOWNERS
Welcome @elv1s to be the maintainer of the PostgreSQL connector. 🎉 
=> add @elv1s as CODEOWNERS

deps/juggler-v3/test.js, deps/juggler-v4/test.js, example/app.js, example/model.js, index.js, lib/discovery.js, lib/migration.js, lib/postgresql.js, lib/transaction.js, package.json, pretest.js, test/init.js, test/postgresql.autocreateschema.test.js, test/postgresql.autoupdate.test.js, test/postgresql.dbdefaults.test.js, test/postgresql.discover.test.js, test/postgresql.filterUndefined.test.js, test/postgresql.initialization.test.js, test/postgresql.mapping.test.js, test/postgresql.migration.test.js, test/postgresql.test.js, test/postgresql.timestamp.test.js, test/postgresql.transaction.test.js
- connect to https://github.com/strongloop-internal/scrum-apex/issues/406
=> chore: update copyrights years

package.json
Dependency module `debug` upgraded from `@3.2.6` to `@4.1.1`.
For testing I've just runned `run-tests`, so here is raw output:
<details>
<summary>Raw Data</summary>
<p>
```clean
2019-04-17T15:54:51.236Z loopback:connector:postgresql Settings {"host":"localhost","port":"5432","database":"test","username":"postgres","password":"1","debug":false,"user":"postgres"}
2019-04-17T15:54:51.302Z loopback:connector:postgresql Settings {"host":"localhost","port":"5432","database":"strongloop","username":"postgres","password":"1","debug":false,"user":"postgres"}
Autocreate schema if not exists
Connection fails: error: database "strongloop" does not exist
It will be retried for the next request.
1) should run migration for custom schema objects
2019-04-17T15:54:51.385Z loopback:connector:postgresql …
```
=> Updated dependency module `debug`

lib/postgresql.js
=> fix: jsdoc

package.json
fixes https://github.com/strongloop/loopback-connector-postgresql/issues/412
=> add missing package chalk

example/app.js, example/model.js, index.js, lib/discovery.js, lib/postgresql.js, lib/transaction.js, pretest.js, test/postgresql.autocreateschema.test.js, test/postgresql.dbdefaults.test.js, test/postgresql.discover.test.js, test/postgresql.filterUndefined.test.js, test/postgresql.initialization.test.js, test/postgresql.mapping.test.js, test/postgresql.migration.test.js, test/postgresql.timestamp.test.js, test/postgresql.transaction.test.js
Related: strongloop-internal/scrum-apex#440
Update the copyrights year in the rest of the packages besides #4596.
The changes are introduced by running the `slt copyright` command. 
=> chore: update copyright year

README.md
=> fix README display on the site

README.md
fixes https://github.com/strongloop/loopback.io/issues/949
=> fix Postgres README layout

README.md
=> fix: fix example property definition

lib/postgresql.js, test/postgresql.test.js
See https://github.com/strongloop/loopback-connector/pull/185
Signed-off-by: Raymond Feng <enjoyjava@gmail.com>
=> Ensure order of and/or clauses are preserved

.github/ISSUE_TEMPLATE/Question.md, .github/workflows/continuous-integration.yaml, .npmrc, CONTRIBUTING.md, README.md, commitlint.config.js, package-lock.json, package.json
As part of https://github.com/strongloop/loopback-next/issues/7595
This PR includes:
- update the repo URL
- add commit linter and code linter in GitHub Actions
- **include package-lock.json** - code linter and commit linter complain about not having package-lock.json file.
=> chore: move repo to loopbackio org

CODEOWNERS
Signed-off-by: Diana Lau <dhmlau@ca.ibm.com>
Add @achrinza and @marioestradarosa as the maintainer of this connector. 🎉 
Thank you @jannyHou @emonddr for contributing to this repo in the past.
Update `CODEOWNERS` file to reflect current status.
=> chore: add Rifa and Mario as codeowners

lib/postgresql.js
Signed-off-by: Francisco Buceta <frbuceta@gmail.com>
- New tests added or existing tests modified to cover all changes
- Code conforms with the [style guide](https://loopback.io/doc/en/contrib/style-guide-es6.html)
=> fix: debug prints the password in plain text

lib/postgresql.js
fixes: https://github.com/loopbackio/loopback-connector-postgresql/issues/504
Signed-off-by: Rifa Achrinza <25147899+achrinza@users.noreply.github.com>
- New tests added or existing tests modified to cover all changes
=> fix: crash with blank `url`

.github/workflows/continuous-integration.yaml
=> chore: add node.js 22 to CI
