- lib/postgresql.js
- test/postgresql.autocreateschema.test.js
Hi!
My models span across several schemas in Postgresql and I've found it handy if schemas are created automatically too during migration process.
> autocreate schema if it does not exist during migration/update

- lib/postgresql.js
- test/postgresql.dbdefaults.test.js
This PR allows to define the default value for a field by the means of database server. It is especially useful when the default value is calculated by a stored procedure.
Example usage is as follows:
simpleUsage.json
```
{
"name": "simpleModel",
"properties": {
"creationDate": {
"type": "Date",
"postgresql": {
"dbDefault": "now()"
}
}
}
}
```
Another, a more complex usecase:
myModel.json
```
{
"name": "myModel",
"base": "PersistedModel",
"options": {
"idInjection": false,
"postgresql": {
"schema": "store",
"table": "item"
}
},
"properties": {
"id": {
"type": "String",
"id": true,
"postgresql": {
"dataType": "uuid",
"dbDefault": "uuid_generate_v4()"
}
}
}
}
```
I quite agree that in many cases the same behaviour can be achieved by Loopback hooks, but still there are cases exist where …
> provide database column default values via Loopback model description

- .editorconfig
I propose enforcing code formatting across different IDEs by providing an .editorconfig file.
For details please refer to http://editorconfig.org
> code formatting settings for multiple IDEs

- example/model.js
- lib/postgresql.js
- test/postgresql.discover.test.js
- test/postgresql.test.js
See https://github.com/strongloop/loopback-datasource-juggler/issues/191
> Add support for GeoPoint type

- test/postgresql.test.js
Forgot to convert regex literals to regex objects in tests.
> Fix regexp operator test

- lib/migration.js
Without this change, we are unable to use postgresql as a datasource for some model relations that use the `embedsOne`. This is because the previous default value for detected JSON data types is `VARCHAR(1024)`. Now by default, the column data type will be `text`, allowing for long JSON strings to be imported into the database.
References issue:  https://github.com/strongloop/loopback-connector-postgresql/issues/131
> - Adds support for long JSON strings when using `embedOne`

- lib/postgresql.js
- test/postgresql.test.js
Connect to strongloop/loopback#2242
When booting app from swagger generator, datasources are setup with ds.lazyConnect = true to avoid connection.
> Lazy connect when booting from swagger

- lib/postgresql.js
- lib/transaction.js
- package.json
This PR upgrades the connector to use pg@6.x. It also fixes an issue for transaction connection releasing.
> Upgrade to pg 6.0.0

- .gitignore
- example/model.js
- index.js
- intl/en/messages.json
- lib/discovery.js
- lib/migration.js
- lib/postgresql.js
- package.json
Connect to strongloop/loopback#2422
> Globalize postgresql

- lib/postgresql.js
- package.json
Connect to https://github.com/strongloop-internal/scrum-loopback/issues/1040
> Use juggler@3 for running tests

- test/init.js
* TEST_ prefix is not used by CI anymore and therefore serve no purpose
* Part of overall goal to standardize env var injection to
MODULE_VARNAME (ie. MONGODB_HOST for example) convention
Connect to https://github.com/strongloop-internal/scrum-loopback/issues/1096
cc @bajtos @rmg @strongloop/fa-db-connectors
> Remove unused prefix from test env vars

- test/init.js
* TEST_ prefix is not used by CI anymore and therefore serve no purpose
* Part of overall goal to standardize env var injection to
MODULE_VARNAME (ie. MONGODB_HOST for example) convention
Backport of #176
cc @bajtos @rmg @strongloop/fa-db-connectors
> Backport: Remove unused prefix from test env vars (#176)

- test/init.js
See https://github.com/strongloop/loopback-connector-postgresql/pull/176#discussion_r82351420
@bajtos PTAL
cc @strongloop/fa-db-connectors
> Accept PGDATABASE env var in test/init.js

- README.md
@0candy 
Per https://github.com/strongloop/loopback.io/issues/158 I'm moving info from docs into the README, as for the other connectors.
> Move info from docs into README

- lib/postgresql.js
- test/postgresql.test.js
connect to https://github.com/strongloop/loopback-connector-postgresql/issues/204
> Use unique param for affectedRows

- lib/postgresql.js
BUG: error: unterminated quoted string at or near \"'\\' ORDER BY \"uuid\"\"
when using like filter.
eg. { where: {name: {like: "%abc%"}}}
> Fix bug when using postgresql 8.x

- README.md
As mentioned in #197 the README information for testing is out of date. This adds brief instructions for how to run tests locally.
cc @jannyHou @crandmck @superkhau
> Update test information in readme

- lib/transaction.js
- test/postgresql.transaction.test.js
A combination of PR #146 which fixes #109 and a switch from explicitly calling `connection.release` to using the built-in `done` callback provided by `pg` to release connection (see [here](https://github.com/brianc/node-postgres/wiki/Transactions))
- #109 
> #109 pool release fix

- lib/postgresql.js
- test/postgresql.test.js
Loopback-datasource-juggler added support for `ILIKE` and `NOT ILIKE` functionality in **v3.1.0**, but the PostgreSQL connector does not update to support them. This pull request adds this functionality by adding a few lines to `lib/postgresql.js` file.
- strongloop/loopback-datasource-juggler#1091
Please let me if any other changes needed.
> Add ILIKE functionality

- lib/migration.js
Refactor discovery test cases
connect to https://github.com/strongloop/loopback-connector/issues/15
> Refactor postgresql migration

- lib/postgresql.js
The current code fails the tests due to invalid escape chars.
- None
> Fix the escape char

- test/init.js
A lot of tests from juggler calls `getDataSource/getSchema` to set up the DB connections without disconnecting them. As a result, postgresql connector tests run out of client connections. This PR allows the reuse of ds.
- None
> Reuse the data source to avoid too many clients

- test/postgresql.dbdefaults.test.js
After switching to a single DataSource instance for the tests, the
InvalidDefault definition remains in the connector's _models
collection. Removed this definition to allow use of db.automigrate
in subsequent tests.
> dbdefaults: Cleanup InvalidDefault def after test

- lib/postgresql.js
- lib/transaction.js
- package.json
- test/init.js
- test/postgresql.transaction.test.js
*Issue*
This fixes a pretty critical issue where operations can occur on non-transactional connections when the user expects them to land in a transaction. Tests added which fail on master but pass here.
*Example use case*:
- Begin a transaction.
- Perform some creates on the transaction
- An external event (e.g. timeout) triggers a rollback
- Additional creates are allowed to continue despite the transaction no longer being active
- These creates still hit the database when the programmer expects them not to as the transaction has rolled back (finished)
*Solution*:
I've added a uuid to each transaction which exists on the transaction itself and is tagged onto the current connection. Whenever the transaction is committed or rolled back ('finished') the id is removed from the connection …
> Fix operations on ended transactions

- package.json
* by listing loopback-connector as a dependency it will be loaded
as a submodule by loopback-connector-postgres when used in a
parent loopback project.  Because we reference objects/constructors
out of loopback-connector, and ask isinstance style questions of
them, they need to resolve to the same constructor
EG:
* App uses loopback-connector and loopback-connector-postgres
* App wishes to generate a loopback-connector.ParameterizedSQL and
pass it to buildDefinition (a where clause), but it is not the same
ParameterizedSQL object (even if loaded from the same lib/version),
because it is in the sub node_packages
NB: this patch should probably be mirrored in loopback-datasource-juggler
To effectively share object models, everyone needs to load the same
library from the same spot.
loopback …
> Add loopback-connector into peer dependencies

- package.json
Revert back strongloop/loopback-connector-postgresql#246 due to `loopback` requiring `loopback-connector` as a default dependency through this module.
connect to https://github.com/strongloop/loopback-workspace/issues/487
> Revert "Add loopback-connector into peer dependencies"

- lib/migration.js
- test/postgresql.test.js
Allow properties that are not an ID to be created as `SERIAL`.
Example use-case: Using GUIDs for a primary id key but still want an auto-incrementing counter value 
- None
> Allow non-id serial properties

- lib/migration.js
- lib/postgresql.js
- test/postgresql.test.js
connect to https://github.com/strongloop/loopback-connector-postgresql/issues/250
- None
> Allow explicit numeric datatype

- README.md
- pretest.js
- setup.sh
- test/init.js
connect to https://github.com/strongloop-internal/scrum-apex/issues/216
> Add docker setup

- lib/postgresql.js
- test/postgresql.test.js
> add explicit typecasts to pattern matching

- README.md
Add documentation to show how to add connection pool settings.
Now you can add min and max pool size and maximum client idle time.
- #261 
- #185
> Add connection pool settings to README.md

- README.md
The node.js driver for postgres returns a `Numeric` type value as a **string** to avoid data precision loss. Since we as the ORM simply just return back the result from the driver, we need to document this behaviour.
connect to https://github.com/strongloop/loopback-connector-postgresql/issues/58
> Add docs on numeric data type

- lib/postgresql.js
- test/postgresql.test.js
Currently, postgresql does not support filtering geopoint fields. This is because postgresql uses the base connector level **buildWhere** function to build the query. Not all SQL connectors have the exact way to compare geopoint values and that is why postgresql fails.
This PR overrides two SQL connector functions **buildWhere** and **_buildWhere** functions and adds the additional check
```js
if (p.type.name === 'GeoPoint')
stmt.merge(columnName + '~=').merge(columnValue);
```
connect to https://github.com/strongloop/loopback-connector-postgresql/issues/126
> Fix geo operator

- lib/postgresql.js
If you set the debug statement in postgresql it is prints to console both queries and data returned from the database.
This PR adds another query scope to only log data :
- `loopback:connector:postgresql:data`
Use the default one `loopback:connector:postgresql` to just log queries.
connected to https://github.com/strongloop/loopback-connector-postgresql/issues/241
> Allow to debug queries only

- lib/migration.js
- test/postgresql.autoupdate.test.js
When using **autoupdate** and altering a column property type, for example from `String` type to `Date`, postgresql requires explicit type casting. This fix allows the connector to handle the type casting when doing such alteration.
connect to https://github.com/strongloop/loopback-connector-postgresql/issues/217
> Fix alter property in autoupdate

- lib/discovery.js
- package.json
- test/postgresql.discover.test.js
If I have an existing table in PostgreSQL with fields with either of type **double precision** or **real**, then discover the table schema as a loopback model, change the model definition and then perform autoupdate, PostgreSQL will throw an error. 
This is because by default, the **double precision** has a precision set to 53 and **real** has a precision set to 24 in postgres and neither of the data types accept parameterized precision values. Both of **double precision** and **real** are child types of **float** which takes parameterized values to determine the children type. 
i.e `float(n)` if n >=1 and n <=24 it is of type **real** and if n >=25 and n <= 53, it is of type **double precision**. Read more [here](https://www.postgresql.org/docs/9.4/static/datatype-numeric.html)
Since …
> Bug in `double precision/real` data type

- lib/discovery.js
- test/postgresql.discover.test.js
When you have an existing table in the database with data types of either **integer**, **bigint** or **smallint** and discover the model definition of that table, it returns back the built-in storage precision of those data types. For example, `smallint` will have a data precision of 16 because the storage size is 2 bytes. Read more [here](https://www.postgresql.org/docs/9.5/static/datatype-numeric.html#DATATYPE-INT).
This is a potential issue because neither of those data types (**integer**, **bigint** or **smallint**) support data precision as an input when creating/altering the table. Hence, updating/migrating the model using the discovered model definition with those data precision values throws a syntax error.
This PR sets the **dataPrecision** field to `null` upon discovering model …
> Fix integer data type

- lib/migration.js
- test/postgresql.autoupdate.test.js
If I have two models with the same name table name, I should be able to `autoupdate` those tables. Currently, `autoupdate` on such scenario fails. This PR fixes the sql statement to allow consideration of the schema before performing the update.
fixes https://github.com/strongloop/loopback-connector-postgresql/issues/287
> Allow migration on different schema

- test/postgresql.transaction.test.js
As outlined in https://github.com/strongloop/loopback-connector/pull/114:  When passing on a transaction object to connector.count(), it does not currently get passed on internally to the SQL `execute()` method, meaning that the count of the table outside the transaction will be counted and a wrong result will be returned.
- https://github.com/strongloop/loopback-connector/pull/114
> Add test for transaction support in count()

- lib/postgresql.js
- lib/transaction.js
- package.json
- test/postgresql.initialization.test.js
Earlier pool release hacks are no longer necessary in pg-pool@2.x.
#197 
> Upgrade to pg@7.

- README.md
- lib/postgresql.js
- test/postgresql.test.js
Add basic support for json querying (where and order-by only - no field limiting to keep it simple).
- #266 (was closed by bot)
Incidentally, I notice this repo doesn't support ES6 syntax online some of the other loopback repos now do 😞
> Add basic json query support

- README.md
- connect to <link_to_referenced_issue>
> Include the SSL Property

- lib/transaction.js
- package.json
- test/postgresql.initialization.test.js
Hello,
In this PR, we upgrade to pg@7 as it has been done on version 3.x
This fixes #311. (When a DB fail over, server goes down until restart)
- connect to #311 
- connect to <link_to_referenced_issue>
- [x ] New tests added or existing tests modified to cover all changes
- [ x] Code conforms with the [style
> Upgrade to pg@7

- lib/transaction.js
This fixes the issue described in #230 
#129
Refer to rollback function in https://github.com/zbarbuto/loopback-connector-postgresql/blob/1361460cea86fadd14a68aa8fe9c55f14ecb9a6d/lib/transaction.js#L58-L86
After the `ROLLBACK` is executed, callback will be sent to the event loop to be executed. Event loop can pick any of the available callbacks to execute. It can pick another function that can do database calls in the same transaction and because releaseConnection has not been called, the statement will execute.
To stop the execution,`connection.txId` should be set to null without waiting for the callback of `ROLLBACK` to be called
> stop execution if rollback is called

- lib/discovery.js
On line 144, dataType "real" and "double precision" are changed to "float", but buildPropertyType has no case for "FLOAT":
https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/discovery.js#L144
This change simply adds a case statement for 'FLOAT'
> Type 'double precision' mapped to String

- .gitignore
- README.md
- lib/migration.js
- test/postgresql.autoupdate.test.js
Support adding and removing foreign key constraints.
Support for adding and removing foreign key constraints. I marked this as WIP since there are a couple of TODO items.
I wanted to get some feedback in the meantime.
- connect to https://github.com/strongloop/loopback-connector-postgresql/issues/348
> feat: add support for create and delete foreign key constraint from model

- lib/migration.js
- test/postgresql.timestamp.test.js
Hello,
If timestamp precision is set, e.g.:
```
"modified": {
"type": "date",
"postgresql": {
"dataType": "timestamp (3) with time zone"
}
}
```
when isActual() is called always return `false` (because `datatypeChanged(propName, oldSettings)` will return `true`). The `"dataPrecision"` property is ignored with Date types.
So, with this fix you can use `"dataPrecision"` to set the precision of a PostgreSQL date to match JavaScript (milliseconds instead of microseconds) without isActual() triggering auto-updates without a reason.
```
"modified": {
"type": "date",
"postgresql": {
"dataType": "timestamp with time zone",
"dataPrecision": 3
}
}
```
> Fix timestamp precision force isActual to false

- lib/migration.js
- test/postgresql.autoupdate.test.js
- Fix multiple foreign keys on same model
- Fix case sensitivity when dropping multiple FK
- If FK property is removed then FK will automatically be dropped, so prevent DROP FK command for this case
- connect to https://github.com/strongloop/loopback-connector-postgresql/issues/359
> fix: multiple fk on a property

- lib/migration.js
- test/postgresql.autoupdate.test.js
Should fix #354
Add the schema name to index name when dropping indices, otherwise the migration script can fail 
due to not being able to find the index, or not being able to re-create the index because it never dropped it.
- connect to 354
Sadly I don't have time to write tests or check the style (I copied the surrounding code style, so should be fine?), but it shouldn't break any existing tests.
> Use canonical index name when dropping

- lib/migration.js
- test/postgresql.autoupdate.test.js
If the foreign key is lower case, it can be created. But if it has any character uppercase. I cannot create. 
I fix it by simple modify `this.escapeName(fk.foreignKey)`
- [] New tests added or existing tests modified to cover all changes
> Fix bug cannot create foreign key

- test/init.js
Add flag to let recently added Juggler tests know that PostgreSQL connector doesn't currently support array data type. See https://github.com/strongloop/loopback-connector-postgresql/issues/342 for more info. Once we have support for it, this flag can be removed.
- [ N/A] New tests added or existing tests modified to cover all changes
> chore: connector flag for no array type support

- .eslintignore
- deps/juggler-v3/package.json
- deps/juggler-v3/test.js
- deps/juggler-v4/package.json
- deps/juggler-v4/test.js
- package.json
- test/init.js
- test/mocha.opts
- test/postgresql.autoupdate.test.js
- test/postgresql.test.js
At the moment, our connectors are installing juggler 3.x to run the test suite. When we make a change to juggler@3, cis-jenkins detects downstream dependency and triggers CI build of connectors with the modified juggler version. When we make a change to juggler's master, no downstream builds are triggered.
In the past, we were maintaining multiple branches to test connectors against different juggler versions. E.g. `loopback-2.x` containing code from "master" but installing juggler 2.x for testing. This is rather impractical, because we don't have bandwidth to update those other branches with changes made to master.
In this pull request, I am reworking connector test setup to execute tests from both juggler versions 3.x and 4.x.
> Run shared tests from both v3 and v4 of juggler

- deps/juggler-v4/test.js
- package.json
- Node.js 6.x has reached EOL
- cis-jenkins has a bug where it runs downstream tests of juggler@4 (supporting Node.js 8+ only) on the minimum Node.js version supported by the connector (Node.js 6), which triggers the check skipping juggler@4 tests.
This change will be published as semver-minor release.
> Drop support for Node.js 6

- deps/juggler-v3/test.js
- deps/juggler-v4/test.js
- example/app.js
- example/model.js
- index.js
- lib/discovery.js
- lib/migration.js
- lib/postgresql.js
- lib/transaction.js
- package.json
- pretest.js
- test/init.js
- test/postgresql.autocreateschema.test.js
- test/postgresql.autoupdate.test.js
- test/postgresql.dbdefaults.test.js
- test/postgresql.discover.test.js
- test/postgresql.filterUndefined.test.js
- test/postgresql.initialization.test.js
- test/postgresql.mapping.test.js
- test/postgresql.migration.test.js
- test/postgresql.test.js
- test/postgresql.timestamp.test.js
- test/postgresql.transaction.test.js
I noticed that this connector is failing CI builds triggered by pull request in loopback-datasource-juggler. In this pull request, I am upgrading all dev-dependencies to the latest versions and fixing eslint violations.
- a266900 updates sinon, mocha, should
- d57001f updates eslint
- 97b3343 contains changes created by `eslint . --fix`, I guess there is not much to review there
- be7e95c is fixing the remaining places that eslint could not fix automatically
- n/a
> Update dev deps + fix linting issues

- .npmrc
Confirmed in discussion via PR #390 that we do not want to commit `package-lock.json`. Thus, we should set `package-lock=false` in `.npmrc`.
- connect to `none`
> chore: set package-lock=false in .npmrc

- lib/migration.js
- test/postgresql.autoupdate.test.js
Seems like syntax error:
- autoupdate not working due to variable is unset
- without this change (just comment this line) Indexes was not updated
https://github.com/strongloop/loopback-connector-postgresql/issues/379
> Fix Index upgrade

- lib/migration.js
- test/postgresql.migration.test.js
- test/postgresql.test.js
- test/postgresql.timestamp.test.js
Run `eslint --fix .` to add trailing commas to function arguments.
The linting errors were discovered by https://github.com/strongloop/loopback-connector/pull/157.
> Fix eslint violations

- lib/postgresql.js
Removes the `process.nextTick()` wrapping the [release callback](https://node-postgres.com/api/pool#pool.connect) after calling `pg.Pool#connect()`.
This was questioned in [this comment](https://github.com/strongloop/loopback-connector-postgresql/pull/52#discussion_r23476901) and never removed. We found test flakiness that was alleviated after removing this unnecessary tick.
> fix(pool): synchronously release pool connection after query results Fix/conn release

- README.md
- lib/migration.js
- test/postgresql.migration.test.js
fixes https://github.com/strongloop/loopback-next/issues/2398
I went through several related issues:
- [postgres canoot generate str type id automatically #811](https://github.com/strongloop/loopback.io/issues/811) 
- [Preserve custom type of auto-generated id property #3602](https://github.com/strongloop/loopback-next/issues/3602)
- [lb3 - Relations on uuid
](https://github.com/strongloop/loopback/issues/4287)
strongloop/loopback-next#2398 is partially fixed in https://github.com/strongloop/loopback-datasource-juggler/pull/1783. 
```
@model()
export class Customer extends Entity {
@property({
type: 'string',
id: true,
useDefaultIdType: false,
generated: true,
})
custid: string;
``` 
The flag `useDefaultIdType: false` is supposed to allow to use custom type of auto-generated id property. …
> fix: allow string type attribute to be auto-generated in Postgres

- test/postgresql.discover.test.js
Schema name should be in PascalCase.
Fixes Postgres failure in https://github.com/strongloop/loopback-datasource-juggler/pull/1819
> fix discovered schema name with pascal case

- test/postgresql.autoupdate.test.js
Connects to https://github.com/strongloop/loopback-datasource-juggler/issues/1816
After investigating, the random CI failures are caused when running autoupdate, the race condition might cause the problem.
**__OR__** 
It failed to drop table (`customer_test2` for example) while doing autouodate, so that it failed to _update_ `customer_test2` because the relation still exists. 
I've simplified the test case to avoid the second situation:
Model `Order` has a foreign key `customerId` refers Model `C2`
-(autoupdate)-> 
Model `Order` has a foreign key `customerId` refers Model `C3`
-(autoupdate)-> 
Model `Order` has fk `customerId` refers Model `C2` and fk `productId` refers to Model `Product`
-(autoupdate)-> 
Model `Order` doesn't have any fks.
Model `Order` has created a foreign key …
> fix Postgres random CI failure

- lib/postgresql.js
- test/postgresql.filterUndefined.test.js
Fixes https://github.com/strongloop/loopback-connector-postgresql/issues/407
> fix: `DEFAULT` for null values in where clause

- package.json
- test/postgresql.discover.test.js
- test/schema.sql
add a test case for Postgres for changes made in https://github.com/strongloop/loopback-connector/pull/171
- checks if the id column name is `demoId`
- checks if the instance can be generated properly with not-null id value 
> tests: checks if column is discovered and mapped correctly

- package.json
**Update dependencies**
- async to ^3.2
- chalk to ^4.0
- uuid to ^7.0
**Upgrade dev dependencies**
- mocha to ^7.1
- sinon to ^9.0
**[SEMVER-MAJOR] Upgrade `pg` to `8.0`**
Notable breaking changes:
- Change default behavior when not specifying `rejectUnauthorized` with the SSL connection parameters. Previously we defaulted to `rejectUnauthorized: false` when it was not specifically included. We now default to `rejectUnauthorized: true`. Manually specify `{ ssl: { rejectUnauthorized: false } }` for old behavior.
- Change default database when not specified to use the `user` config option if available. Previously `process.env.USER` was used.
See pg's changelog for the full list of breaking changes.
https://github.com/brianc/node-postgres/blob/master/CHANGELOG.md#pg800
👉 [Read and sign the …
> [SEMVER-MAJOR]: upgrade dependencies

- README.md
In preparation for a new semver-major release (see https://github.com/strongloop/loopback-connector-postgresql/pull/432), I am updating the README with information about LTS versions. The content is written to match the status after the new major version is published.
> README: add info about LTS policy

- lib/postgresql.js
- test/postgresql.test.js
This pull request fixes a bug I encountered with the PostgeSQL connector when updating the value of a model's property of type array of strings.
When creating the model no issue occurs but when updating it the value stored in the column turns into an invalid array, for example '{ "A","B","C"}' instead of '["A","B","C"]. After a bit of investigating I thought it was linked to the juggler giving the value in the query as an Array instead of a List object but even after fixing this the issue was still there. So I figured that it must be in the connector and changed it there. (This may be related to #342)
If you think this change belong somewhere else just tell me and I'll move it.
The added unit test just check that the object is still deserialisable after an update. It fails without the …
> Fix serialization of arrays of string in update

- README.md
While working on https://github.com/strongloop/loopback-next/issues/4877, I realized that the PostgreSQL connector overview we have in LB4 site is not a good fit as:
- LB4 uses different cli to generate the datasource
- LB4 has different way to define models
- LB4 code are mainly written in Tsc
- LB4 doesn't have all options use in LB3
Inspired by markdown collapsible section, I think we can fold the LB3 content and mainly display the LB4 in these connector README docs
<details>
<summary><strong>Click to expand!</strong></summary>
Since we are using one doc for 2 different versions.
And (hopefully) less people are using LB3
</details>
**Edit:**
Besides the collapsible block, I also update the auto-migration/discovery part.
The following is part of the preview of the collapsible section …
> docs: update readme with more lb4 form and hide lb3 form

- README.md
In the Travis job running on loopback.io, it has errors:
```
Liquid Exception: Could not locate the included file 'tips.html' in any of ["/home/travis/build/strongloop/loopback.io/_includes", "/home/travis/.rvm/gems/ruby-2.5.3/gems/jekyll-theme-primer-0.5.4/_includes"]. Ensure it exists in one of those directories and is not a symlink as those are not allowed in safe mode. in /_layouts/readme.html
```
`tips.html` referenced in this README should be `tip.html`.
> fix: use tip.html

- .mocharc.json
- package.json
- setup.sh
- test/mocha.opts
- `eslint` to 7.x
- `mocha` to 8.x
- `uuid` to 8.x
- `loopback-connector` to 5.x
- New tests added or existing tests modified to cover all changes
> Update dependencies to latest

- README.md
- lib/postgresql.js
- test/postgresql.test.js
- Adds new filter named as contains.
- This filter will search on Array type fields in Postgres DB.
Include references to all related GitHub issues and other pull requests, for example:
Fixes #342
> array_type_field_filter: Add new contains filter to search on Array type field

- lib/postgresql.js
- test/postgresql.initialization.test.js
As documented in https://node-postgres.com/api/pool#events, it is _very_ important to attach a listener to the Pg Pool `error` event if you don't want your app to randomly crash/exit if something happens to idle connections in the pool (e.g. someone restarts your PostgreSQL server/pgBouncer/etc., or server times out your idle connection). Currently `loopback-connector-postgresql` provides no means of doing this, which makes writing stable apps that use it hard.
This PR adds an optional `onError` property to the connector settings, which can be one of:
* The string `ignore` to report any errors via `debug`, and otherwise ignore them
* An app-provided listener function to connect to the pool
It also, as a side item, fixes a broken link to the node-postgres documentation.
*Testing notes:* …
> fix: enable pool error handling

- README.md
- lib/discovery.js
- lib/migration.js
- test/postgresql.autoupdate.test.js
Allow setting `on delete` rule on foreign key constraints.
Update foreign key discovery query to add on delete rules mainly for testing purpose.
> Add on delete options on FK constraints

- lib/migration.js
When `PostgreSQL.prototype.getDropForeignKeys` gets called with duplicated foreign keys, an invalid `ALTER TABLE` statement gets created. This is because the duplicates are mapped to multiple `DROP CONSTRAINT fk_key` SQL actions, e.g.:
```sql
-- This will throw an error
ALTER TABLE "public"."foo"
DROP CONSTRAINT "fk_duplicatedKey",
DROP CONSTRAINT "fk_duplicatedKey",
DROP CONSTRAINT "fk_duplicatedKey",
DROP CONSTRAINT "fk_otherKey"
```
As the `DROP CONSTRAINT` actions are run sequentially, when the first action gets executed by PostgreSQL, the next one (for the same, but already dropped key) will no longer cause an SQL error thanks to the added IF EXISTS check:
```sql
-- This is valid SQL
ALTER TABLE "public"."foo"
DROP CONSTRAINT IF EXISTS "fk_duplicatedKey",
DROP CONSTRAINT IF EXISTS …
```
> Defensively drop constraints during migrations

- README.md
- lib/postgresql.js
- test/postgresql.test.js
- Adds an operators for full text search based on the `@@` operator in PostgreSQL.
Fixes #484
> feat(operators): add fts match using postgres @@ operator

- lib/postgresql.js
- test/postgresql.test.js
Prior to v5.2.1, empty and/or fields were handled gracefully. After the upgrade to v5.2.1, this change and the connector would through an error `syntax error at or near ")"`
Fixes https://github.com/loopbackio/loopback-connector-postgresql/issues/483
> fix: disregard empty and/or fields in buildSelect

- lib/postgresql.js
- package-lock.json
- package.json
- pretest.js
- test/postgresql.test.js
BREAKING CHANGE: This drops explicit, documented support for Node.js v10, v11, v12, v13, v15, v17
Signed-off-by: Samarpan Bhattacharya <this.is.samy@gmail.com>
1. Added support for multiple insert in one query using createAll() of connector. 
2. Updated some existing tests for name field of id column and added some too. This was done to test if the new getInsertedIds method works in those cases or not.
Fixes #523
See also https://github.com/loopbackio/loopback-next/issues/3357
> feat(postgresql): add support for multiple insert in one query using createAll() of connector

- lib/migration.js
Currently `dbDefault` metadata property value is used only on columns when creating table, but not when altering it. Changed that to match behaviour in both cases.
> fix(migration): add dbDefault also when altering table

- lib/postgresql.js
pg-pool requires attaching an error handler to each connection acquired from the pool, which will handle connection-level errors. Without it, the process ends up crashing whenever the connection is interrupted (e.g. database failover).
This fact can be observed in pg-pool:
- newClient [1] and _release (back to the pool) [2] attaches an "idleListener" error handler which upon encountering a connection error, destroys the connection / removes it from the pool, and re-emits [3]
- _acquireClient removes the "idleListener", leaving the returned connection without an error handler [4]
This PR is in response to production outages we have faced during Aurora PostgreSQL failovers, with the unexpected disconnections for actively-used connections turning error emits into unhandled exceptions and …
> fix: unhandled connection errors

- lib/discovery.js
- test/postgresql.discover.test.js
- test/schema.sql
With the current version of Postgres, we can have the id as auto-increment by adding an identity constraint with the value set to ALWAYS. This PR enables the connector to return the `generated` as true if a column is set to be an auto-increment with this constraint.
> fix: return auto-increment as generated

- README.md
- lib/postgresql.js
- test/postgresql.test.js
- adds operators `containedBy` and `containsAnyOf` using the `<@` and  `&&` operators in postgresql.
- Restructured array operators tests to avoid duplication
- added tests for `containedBy` and `containsAny`
- based on original PR by [Hazım Dikenli](https://github.com/hazimdikenli) - https://github.com/loopbackio/loopback-connector-postgresql/pull/640
Co-authored-by: Hazım Dikenli <hazim.dikenli@atez.com.tr>
> feat(operators): add containedBy and containsAnyOf operators

- lib/postgresql.js
> Remove error event listener before releasing connection back to pool

- lib/postgresql.js
- package-lock.json
- package.json
- test/postgresql.attachErrorHandler.test.js
Our application was crashing when the database connection unexpectedly failed. This happened because:
1. We were previously using removeAllListeners('error'), which unintentionally removed the pg library's error handlers.
2. This left connection termination errors unhandled, leading to app crashes which uses this connector
We've fixed this by:
1. Completely removing the removeAllListeners('error') call within the connector. This ensures that the pg library's built-in error handling for connection issues remains active.
2. We now only add our connector's specific error listener if the pg client doesn't already have any error listeners attached (!pg.listenerCount('error')). This prevents us from creating too many listeners (addressing past MaxEventListeners warnings) while ensuring all …
> fix: Connection terminated unexpectedly error not caught in on error handler
